buildPack: maven-lib
pipelineConfig:
  env:
  - name: COVERALLS_TOKEN
    value: sDzHuWARi93T3JN7QIeG6KELKdmumYOC4
  - name: JS_CODE_SUBDIR
    value: react-app
  - name: POST_BUILD_COMMAND
    value: echo Post-build
  - name: PRE_BUILD_COMMAND
    value: echo Pre-build
    
pipelines:
     release:
       build:
         steps:
         - command:  tail -f /dev/null
           name: keep-alive
