name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init vars
      id: vars_step
      uses: ./.github/actions/env-vars

    - name: print
      run: "echo Sha: ${{ steps.vars_step.outputs.sha-short }}   Branch: ${{ steps.vars_step.outputs.branch }}"
